from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = [
    'fs.c',
    'httpd.c',
    'httpd_cgi_ssi.c',
    'web_server.c',
]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
